name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - run: docker build --tag table-tennis-table .
      - run: docker run table-tenis-table