name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker build --tag table-tennis-table --target test .
      - run: docker run table-tenis-table --target test
      - run: ./gradlew test